apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ocis
  namespace: home
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ocis.pavel-usanli.online`)
      kind: Rule
      services:
        - name: ocis
          port: 80
  tls:
    certResolver: cloudflare