apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ocis
  namespace: home
spec:
  entryPoints:
    - private
  routes:
    - match: Host(`ocis.internal`)
      kind: Rule
      services:
        - name: ocis
          port: 80
