apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: internal

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - trivy-report-exporter-cron.yaml
  - trivy-pvc-resports.yaml
  - trivy-report-rbac.yaml