apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-browser
  namespace: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-browser
  template:
    metadata:
      labels:
        app: file-browser
    spec:
      containers:
        - name: file-browser
          image: hurlenko/filebrowser:latest
          ports:
            - containerPort: 8080

          env:
            - name: FB_BASE_URL
              value: "/"

          volumeMounts:
            - name: data
              mountPath: /data

            - name: db
              mountPath: /config

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: file-browser-data

        - name: db
          persistentVolumeClaim:
            claimName: file-browser-db
