apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: file-browser-public
  namespace: internal
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`files.pavel-usanli.online`)
      kind: Rule
      priority: 10
      services:
        - name: file-browser
          port: 80

  tls:
    certResolver: cloudflare
