apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: file-browser
  namespace: home
spec:
  entryPoints:
    - private
  routes:
    - match: Host(`files.internal`)
      kind: Rule
      priority: 10
      services:
        - name: file-browser
          port: 80
