apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: internal

resources:
  - storage.yaml
  - deployment.yaml
  - service.yaml
  - ingress-internal.yaml
#  - ingress-public.yaml
