apiVersion: v1
kind: Service
metadata:
  name: file-browser
  namespace: home
spec:
  selector:
    app: file-browser
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
