apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: owncloud
  namespace: home
spec:
  entryPoints:
    - private
  routes:
    - match: Host(`owncloud.internal`)
      kind: Rule
      priority: 10
      services:
        - name: owncloud
          port: 80
