apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home

resources:
  - ingress.yaml
  - owncloud-pv.yaml
  - owncloud-mariadb.yaml
  - owncloud-redis.yaml
  - owncloud-deployment.yaml
