---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: owncloud
  namespace: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: owncloud
  template:
    metadata:
      labels:
        app: owncloud
    spec:
      containers:
        - name: owncloud
          image: owncloud/server:latest
          env:
            - name: OWNCLOUD_DOMAIN
              value: "owncloud.internal"
            - name: OWNCLOUD_TRUSTED_DOMAINS
              value: "owncloud.internal"
            - name: OWNCLOUD_DB_TYPE
              value: "mysql"
            - name: OWNCLOUD_DB_NAME
              value: "owncloud"
            - name: OWNCLOUD_DB_USERNAME
              value: "owncloud"
            - name: OWNCLOUD_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: owncloud-secrets
                  key: db-password
            - name: OWNCLOUD_DB_HOST
              value: "mariadb"
            - name: OWNCLOUD_ADMIN_USERNAME
              value: "admin"
            - name: OWNCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: owncloud-secrets
                  key: admin-password
            - name: OWNCLOUD_MYSQL_UTF8MB4
              value: "true"
            - name: OWNCLOUD_REDIS_ENABLED
              value: "true"
            - name: OWNCLOUD_REDIS_HOST
              value: "redis"
          volumeMounts:
            - name: files
              mountPath: /mnt/data
          livenessProbe:
            exec:
              command: ["/usr/bin/healthcheck"]
            initialDelaySeconds: 60
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command: ["/usr/bin/healthcheck"]
            initialDelaySeconds: 30
            timeoutSeconds: 10
          ports:
            - containerPort: 8080
      volumes:
        - name: files
          persistentVolumeClaim:
            claimName: owncloud-files
---
apiVersion: v1
kind: Service
metadata:
  name: owncloud
  namespace: home
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: owncloud
