apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: router
  namespace: internal
spec:
  entryPoints:
    - private
  routes:
    - match: Host(`router.internal`)
      kind: Rule
      services:
        - name: router-external
          port: 80
