apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: adguard
  namespace: internal
spec:
  entryPoints:
    - private
  routes:
    - match: Host(`adguard.internal`)
      kind: Rule
      services:
        - name: adguard-external
          port: 8082
