apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pgadmin
  namespace: internal
spec:
  entryPoints:
    - private
  routes:
    - match: Host(`pgadmin.internal`)
      kind: Rule
      services:
        - name: pgadmin-external
          port: 9001
