apiVersion: apps/v1
kind: Deployment
metadata:
  name: battleship
  namespace: public
spec:
  replicas: 1
  selector:
    matchLabels:
      app: battleship
  template:
    metadata:
      labels:
        app: battleship
    spec:
      containers:
        - name: battleship
          image: kalpak44/battleship-party:02f76fdb8171d87975ea1595ba30a2701c3b52c9
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
