apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: battleship
  namespace: public
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`battleship.pavel-usanli.online`)
      kind: Rule
      priority: 10
      services:
        - name: battleship
          port: 8000

  tls:
    certResolver: cloudflare
