apiVersion: v1
kind: Service
metadata:
  name: battleship
  namespace: public
spec:
  selector:
    app: battleship
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
