apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin
  namespace: home
spec:
  entryPoints:
    - private
  routes:
    - match: Host(`jellyfin.internal`)
      kind: Rule
      services:
        - name: jellyfin
          port: 8096
          scheme: http
