apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: weave-gitops
  namespace: gitops
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`flux.pavel-usanli.online`)
      kind: Rule
      services:
        - name: weave-gitops
          port: 9001
  tls:
    certResolver: letsencrypt
