apiVersion: apps/v1
kind: Deployment
metadata:
  name: bunker
  namespace: public
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bunker
  template:
    metadata:
      labels:
        app: bunker
    spec:
      containers:
        - name: bunker
          image: kalpak44/bunker-party:87bd9bea362676b92d7890ab029de701aa918338
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
