apiVersion: apps/v1
kind: Deployment
metadata:
  name: bunker
  namespace: public
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bunker
  template:
    metadata:
      labels:
        app: bunker
    spec:
      containers:
        - name: bunker
          image: kalpak44/bunker-party:839d8064ab06d0a8fd7a7188be3d48ece4e1d0da
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
