apiVersion: apps/v1
kind: Deployment
metadata:
  name: bunker
  namespace: public
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bunker
  template:
    metadata:
      labels:
        app: bunker
    spec:
      containers:
        - name: bunker
          image: kalpak44/bunker-party:0c93e2ca2677a2ba24994ae62295e8cf8a40a830
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
