apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bunker
  namespace: public
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`bunker.pavel-usanli.online`)
      kind: Rule
      priority: 10
      services:
        - name: bunker
          port: 8000

  tls:
    certResolver: cloudflare
