apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portainer
  namespace: internal
spec:
  entryPoints:
    - private
  routes:
    - match: Host(`portainer.internal`)
      kind: Rule
      services:
        - name: portainer-external
          port: 9000
