apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: internal
spec:
  entryPoints:
    - private
  routes:
    - match: Host(`grafana.internal`)
      kind: Rule
      priority: 10
      services:
        - name: grafana
          port: 80
