apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: internal

resources:
  - ingress.yaml
  - node-exporter-daemonset.yaml
  - node-exporter-service.yaml
  - grafana-helmrepo.yaml
  - grafana-release.yaml
  - prometheus-config.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml
  - grafana-datasource-prometheus.yaml
  - trivy-dashboard.yaml