apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: internal
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:

      ####################################################################
      # NODE EXPORTER (HOST METRICS)
      ####################################################################
      - job_name: "node-exporter"
        static_configs:
          - targets:
              - node-exporter.internal.svc:9100

      ####################################################################
      # KUBERNETES SERVICES (FOR TRIVY, FUTURE EXPORTERS)
      ####################################################################
      - job_name: "kubernetes-services"
        kubernetes_sd_configs:
          - role: service

        relabel_configs:
          # keep only trivy-operator service
          - source_labels: [__meta_kubernetes_namespace]
            action: keep
            regex: trivy-system

          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: trivy-operator

          # use service port named "metrics" or default
          - source_labels: [__meta_kubernetes_service_port_name]
            action: keep
            regex: metrics|http|https
