apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: internal
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:

      ####################################################################
      # NODE EXPORTER (HOST METRICS)
      ####################################################################
      - job_name: "node-exporter"
        static_configs:
          - targets:
              - node-exporter.internal.svc:9100

      ####################################################################
      # TRIVY OPERATOR (HEADLESS SERVICE â†’ ENDPOINTS)
      ####################################################################
      - job_name: "trivy-operator"
        kubernetes_sd_configs:
          - role: endpoints

        relabel_configs:
          # keep only trivy-operator endpoints
          - source_labels: [__meta_kubernetes_namespace]
            action: keep
            regex: trivy-system

          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: trivy-operator

          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: metrics

          ##################################################################
          # FORCE SCRAPE PORT TO 8080 (TRIVY METRICS PORT)
          ##################################################################
          - source_labels: [__address__]
            target_label: __address__
            regex: (.+):\d+
            replacement: $1:8080
