apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - traefik-helmrepo.yaml
  - traefik-release.yaml
  - traefik-crds-helmrepo.yaml
  - traefik-crds-release.yaml
