apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Infrastructure
  - infra/flux-system
  - infra/traefik
  - infra/nfs
  # Public services
  - public/namespace.yaml
  - public/spy-game
  - public/bunker-game
  - public/battleship-game
   # Internal services
  - internal/namespace.yaml
  - internal/nfs-pvc.yaml
  - internal/busybox-nfs-test.yaml
  - internal/landing-page
  - internal/adguard
  - internal/portainer
  - internal/router
  - internal/grafana
#  - internal/file-browser
#  - internal/ocis