apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infra/flux-system
  - infra/traefik
  - internal

  - internal/landing-page
  - internal/adguard
  - internal/portainer
  - internal/router
  - internal/grafana