apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Infrastructure
  - infra/flux-system
  - infra/traefik
  # Public services
  - public/test
   # Internal services
  - internal/landing-page
  - internal/adguard
  - internal/portainer
  - internal/router
  - internal/grafana